version: 2.1

jobs:
  build:
    docker:
      -   image: circleci/php:7.2-cli
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: make
          command: make
      - save_cache:
         key: composer-v1-{{ checksum "composer.lock" }}
         paths:
           - vendor

workflows:
  version: 2
  build:
    jobs:
      - build
